INSERT OR IGNORE INTO homestays (name,slug,city,state,google_rating,google_review_count,source_name,source_url,status,google_data_checked_at)
SELECT name,slug,city,state,rating,review_count,'Google Maps via SeekHomestay','https://seekhomestay.my/','active','2026-08-30'
FROM (VALUES
('Bali Residences Sea View Suites Melaka','google-top-001','Melaka','Melaka',5.0,4854),
('Country Garden Danga Bay Sea View by Stayrene','google-top-002','Johor Bahru','Johor',5.0,2710),
('Central Residence Homestay @ Kuala Lumpur','google-top-003','Kuala Lumpur','Kuala Lumpur',5.0,537),
('Timber Homestay Mount Austin • Pool • Karaoke','google-top-004','Johor Bahru','Johor',5.0,410),
('Windmill Upon Hills by BYON','google-top-005','Genting Highlands','Pahang',5.0,395),
('123 Guest House | Kuantan, Pahang.','google-top-006','Kuantan','Pahang',5.0,348),
('Trion Premium Suites @ KL','google-top-007','Kuala Lumpur','Kuala Lumpur',5.0,312),
('Exclusive 3 Bedroom Homestay @Kuala Lumpur','google-top-008','Kuala Lumpur','Kuala Lumpur',5.0,277),
('Penthouse Secret Garden de Cameron, Night Market','google-top-009','Tanah Rata','Pahang',5.0,265),
('HYVE SOHO Cyberjaya Comfort Stay – 2BR 3pax','google-top-010','Putrajaya','Putrajaya',5.0,220),
('Mawar Homestay Camelia Kuala Terengganu (BANGLO 5 BILIK)','google-top-011','Kuala Terengganu','Terengganu',5.0,219),
('VLA 16 HOMESTAY PUTRAJAYA DWIPUTRA','google-top-012','Putrajaya','Putrajaya',5.0,190),
('Ammara homestay 3 @ Palas Horizon kea farm','google-top-013','Kea Farm','Pahang',5.0,188),
('Luxury Troika Kota Bharu by Aura Troika - Two-Bedroom Apartment','google-top-014','Kota Bharu','Kelantan',5.0,172),
('Best Moments studio balcony- Imperium Resident - One-Bedroom Apartment','google-top-015','Kuantan','Pahang',5.0,150),
('Sembilan Langkawi - Villa','google-top-016','Langkawi','Kedah',5.0,117),
('Dual Key 3BR at Macalister 218 Georgetown 32 WL - Three-Bedroom Apartment','google-top-017','Penang / Georgetown','Penang',5.0,96),
('Rex 3Bedroom 5-10pax 5min Drive to Vivacity','google-top-018','Kuching','Sarawak',5.0,95),
('Wakaf Homestay Rukaiyah Al Mansouri','google-top-019','Mersing','Johor',5.0,93),
('impianKU at HYVE SOHO Cyberjaya Studio 4pax Wifi','google-top-020','Putrajaya','Putrajaya',5.0,92),
('Golden Troika Kota Bharu -2 bedrooms','google-top-021','Kota Bharu','Kelantan',5.0,86),
('Rasa Sayang at The Loft Imago','google-top-022','Kota Kinabalu','Sabah',5.0,84),
('NH Legacy Homestay Mersing','google-top-023','Mersing','Johor',5.0,83),
('KSL City Mall 7-9pax Netflix｜SmartTV 65inch（K23）','google-top-024','Johor Bahru','Johor',5.0,82),
('MW Imperio Residence 2Bedroom Sea View Private Jacuzzi Villa - Two-Bedroom Apartment','google-top-025','Melaka','Melaka',5.0,82),
('SY vivacity homestay @ service apartment - Three-Bedroom Apartment','google-top-026','Kuching','Sarawak',5.0,79),
('DS Vivacitymall Jazz Suite 1101','google-top-027','Kuching','Sarawak',5.0,78),
('Homestay Mersing Anid','google-top-028','Mersing','Johor',5.0,77),
('KSL CityMall 7-9pax Netflix｜SmartTV 65inch (K26)','google-top-029','Johor Bahru','Johor',5.0,77),
('RiverView 8PAX 2BR in KBtown Netflix, Wi-Fi B-3A-5','google-top-030','Kota Bharu','Kelantan',5.0,75),
('KSL CityMall 7-9pax Netflix｜SmartTV 65inch (K20)','google-top-031','Johor Bahru','Johor',5.0,74),
('TH Ipoh Homestay@Simee, 10pax, 8mins to attraction','google-top-032','Ipoh','Perak',5.0,64),
('Tiong Trove Family Farm','google-top-033','Ipoh','Perak',5.0,60),
('Sweet Loft Homestay','google-top-034','Johor Bahru','Johor',5.0,57),
('Meru Paradise Homestay','google-top-035','Ipoh','Perak',5.0,55),
('KSL CityMall 7-9pax Netflix｜SmartTV 65inch K232)','google-top-036','Johor Bahru','Johor',5.0,53),
('TRANQUIL ARCADIA HOMESTAY by Desaru','google-top-037','Desaru','Johor',5.0,45),
('LOW SEASON PROMOTION! 4B12B Mountainville Bungalow - Four-Bedroom House','google-top-038','Ipoh','Perak',5.0,44),
('Blissful Homestay @Horizon Ipoh','google-top-039','Ipoh','Perak',5.0,42),
('Ria Homestay','google-top-040','Johor Bahru','Johor',5.0,37),
('DendellionStay Tg Genting, Mersing, Johor','google-top-041','Mersing','Johor',5.0,36),
('Glenmarie Austin [15pax]Mount Austin Family Stay','google-top-042','Johor Bahru','Johor',5.0,35),
('Tepak Nusuk Private Pool Homestay 5 Beds 4 Baths','google-top-043','Kota Bharu','Kelantan',5.0,35),
('Desaru Caleessa Homestay','google-top-044','Desaru','Johor',5.0,33),
('Homestay langkawi By LangkawiGO','google-top-045','Langkawi','Kedah',5.0,32),
('GederHome Mersing','google-top-046','Mersing','Johor',5.0,30),
('A Spacious 7BR Home w/ Private Swimming Pool','google-top-047','Langkawi','Kedah',5.0,26),
('PARTY HAUS for 22pax 7 bedrooms 8 toilets karaoke','google-top-048','Johor Bahru','Johor',5.0,26),
('Renovated Bluesky D&N Homestay 光@暗 小舍','google-top-049','Langkawi','Kedah',5.0,25),
('Adam''s Homestay Desaru','google-top-050','Desaru','Johor',5.0,24)) AS v(name,slug,city,state,rating,review_count);
