WITH v(name,slug,city,state,rating,review_count) AS (
VALUES
('The Best Rumah Amaan in Langkawi','google-top-051','Langkawi','Kedah',5.0,23),
('Ipoh South Homestay 8-16pax 10mins to attraction','google-top-052','Ipoh','Perak',5.0,22),
('D’Ipoh Homestay','google-top-053','Ipoh','Perak',5.0,20),
('Tiara Homestay Langkawi','google-top-054','Langkawi','Kedah',5.0,20),
('Homestay Murah Villa Az Zahra Langkawi','google-top-055','Langkawi','Kedah',5.0,19),
('Single Storey Bungalow 12 pax - Four-Bedroom House','google-top-056','Ipoh','Perak',5.0,18),
('Homestay Sweet','google-top-057','Mersing','Johor',5.0,17),
('Amjad Homestay - Entire Place','google-top-058','Kota Bharu','Kelantan',5.0,16),
('Ikiru 18 Private Saltwater Pool Villa, 3 Ensuite BR, Outdoor BBQ, 5 mins to Beach - Three-Bedroom Villa','google-top-059','Langkawi','Kedah',5.0,16),
('La Villa Langkawi - Private Pool - One-Bedroom Villa with Private Pool','google-top-060','Langkawi','Kedah',5.0,16),
('The Langkawi Luxury - Premier Pool Villa','google-top-061','Langkawi','Kedah',5.0,16),
('The heaven in sunway ipoh - Bungalow','google-top-062','Ipoh','Perak',5.0,16),
('Ayu Pelangi Indah Near Desa Tebrau Mount Austin','google-top-063','Johor Bahru','Johor',5.0,15),
('Alunan padi homestay','google-top-064','Langkawi','Kedah',5.0,14),
('Desaru Kids Water Slide Pool & BBQ Homestay','google-top-065','Desaru','Johor',5.0,12),
('Ipoh stadium 1min/wahkeongpark simee 18pax bungalow cottage','google-top-066','Ipoh','Perak',5.0,12),
('DESARU HOMESTAY & HOME TO STAY','google-top-067','Desaru','Johor',5.0,11),
('Gran Estancia Villa @ RR JBcity','google-top-068','Johor Bahru','Johor',5.0,11),
('HOMESTAY Comfy CONDO (Ground) Pool View Manhattan','google-top-069','Ipoh','Perak',5.0,11),
('Homestay in Ipoh ~ Megram Cozy Stay Ipoh ~ RM250/night ~ 1-20 pax','google-top-070','Ipoh','Perak',5.0,10),
('1Residence Guest House Kota Bharu','google-top-071','Kota Bharu','Kelantan',5.0,8),
('Cheers Chalet - Deluxe Triple Room','google-top-072','Mersing','Johor',5.0,8),
('HAPPY GATHER HOMESTAY - Four-Bedroom House','google-top-073','Ipoh','Perak',5.0,8),
('Royale Chulan Cherating Villa - Family Villa','google-top-074','Cherating','Pahang',5.0,8),
('Studio Exclusive (Kota Bharu City Point) - One-Bedroom Apartment','google-top-075','Kota Bharu','Kelantan',5.0,8),
('The Tudor - Classic Suite','google-top-076','Ipoh','Perak',5.0,7),
('NineInn Homestay: Bungalow Swimming Pool Villa','google-top-077','Johor Bahru','Johor',5.0,6),
('Villa Family - Private Pool - Entire Place','google-top-078','Kota Bharu','Kelantan',5.0,6),
('AZ’s Cosy House to Stay @ Kubang Kerian','google-top-079','Kota Bharu','Kelantan',5.0,5),
('Homestay: Ipoh Garden 39','google-top-080','Ipoh','Perak',5.0,5),
('Nazrins Studio Apartment','google-top-081','Kota Bharu','Kelantan',5.0,5),
('Raihan Homestay Kubang Kerian, Free Wifi - Three-Bedroom House','google-top-082','Kota Bharu','Kelantan',5.0,5),
('City View Apartment rent','google-top-083','Ipoh','Perak',5.0,4),
('Homestay: Ipoh Garden 9','google-top-084','Ipoh','Perak',5.0,4),
('Ipoh Town Canning Garden Football Table ~ Pets OK','google-top-085','Ipoh','Perak',5.0,4),
('KLCC View Bungalow for party','google-top-086','Janda Baik','Pahang',5.0,4),
('LUXURY Modern House Kubang Kerian UNIFI 4 Bedrooms - Four-Bedroom House','google-top-087','Kota Bharu','Kelantan',5.0,4),
('Ammar Troika Homestay Kota Bharu','google-top-088','Kota Bharu','Kelantan',5.0,3),
('Shizukesa No Nojo (Farm of Tranquility)','google-top-089','Ipoh','Perak',5.0,3),
('T T Kuching Homestay - Four-Bedroom House','google-top-090','Kuching','Sarawak',5.0,3),
('Ameera family homestay - Entire Place','google-top-091','Kota Bharu','Kelantan',5.0,2),
('Homestay Camelia Kuala Terengganu','google-top-092','Kuala Terengganu','Terengganu',4.9,2107),
('The Coco Journey Glamping','google-top-093','Melaka','Melaka',4.9,439),
('Auranad Troika Exclusive Apartment','google-top-094','Kota Bharu','Kelantan',4.9,97),
('HOMESTAY MURAH IPOH 🏡 MAMAHomestay','google-top-095','Ipoh','Perak',4.9,63),
('Homestay Ipoh d''Hakimi Sari 11','google-top-096','Ipoh','Perak',4.9,50),
('Homestay Tok Puan (IPOH)','google-top-097','Ipoh','Perak',4.9,46),
('MIA HOMESTAY IPOH (MUSLIM FRIENDLY)','google-top-098','Ipoh','Perak',4.9,38),
('Homestay Ipoh d’Hakimi Sari 34','google-top-099','Ipoh','Perak',4.9,36),
('AiNad Guesthouse Ipoh','google-top-100','Ipoh','Perak',4.9,30)
)
INSERT OR IGNORE INTO homestays (name,slug,city,state,google_rating,google_review_count,source_name,source_url,status,google_data_checked_at)
SELECT name,slug,city,state,rating,review_count,'Google Maps via SeekHomestay','https://seekhomestay.my/','active','2026-08-30'
FROM v;